version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      ENV_NAME: production
    ports:
      - '3000:3000'
    networks:
      - app_net

networks:
  app_net:

